apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000          # Port exposed by the service (external)
      targetPort: 3000    # Port where the app container listens (internal)
  type: NodePort         # NodePort to expose it externally
